dist: focal

services:
  - docker

before_script:
  - mkdir -p ~/.docker/cli-plugins
  - wget -O - https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-amd64 > ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx
  - docker run --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
  - docker buildx create --use --name mybuilder

script:
  - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
  #- cd ./docker/elasticsearch/
  #- docker buildx build --platform linux/amd64,linux/arm64 -t odidev/elasticsearch:latest -t odidev/elasticsearch:latest --push .;
  - cd ./docker/elasticsearch_5x
  #- cd ../elasticsearch_5x
  - docker buildx build --platform linux/amd64,linux/arm64 -t odidev/elasticsearch_5x:latest -t odidev/elasticsearch_5x:latest --push .;
